name: Sync with Upstream

on:
  push:
    branches:
      - main

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.email "jyf20100214@outlook.com"
        git config --global user.name "Jyf0214"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git

    - name: Fetch from upstream
      run: |
        git fetch upstream

    - name: Merge changes from upstream
      run: |
        git merge upstream/main --allow-unrelated-histories

    - name: Remove GitHub Actions and specified files/folders
      run: |
        # List the files and folders you want to exclude
        git rm -r --ignore-unmatch '.github/*'
        git rm -r --ignore-unmatch 'path/to/your/specific/file_or_folder'

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Sync with upstream and remove specified files/folders"
        git push origin main
