name: Sync with Upstream

on:
  push:
    branches:
      - main

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git

    - name: Fetch from upstream
      run: |
        git fetch upstream

    - name: Merge changes from upstream
      run: |
        git merge upstream/main --no-commit --no-ff

    - name: Remove GitHub Actions and specified files/folders
      run: |
        # List the files and folders you want to exclude
        git rm --cached -r --ignore-unmatch '.github/workflows/*'
        git rm --cached -r --ignore-unmatch 'public/*'

    - name: Commit and push changes
      run: |
        git commit -m "Sync with upstream and remove specified files/folders" || echo "No changes to commit"
        git push origin main
